### ISSUE TITLE
Missing tslib

### ISSUE THREAD

**Issue by ar2rsawseen** [Apifier/xlsx-stream#28]
Hello
it feels like I am missing something, as I don't see anyone raising this issue, but
our pipelines started to fail when testing for the latest version of xlsx-stream "[Bump xlsx-write-stream from 1.0.0 to 1.0.2](https://github.com/Countly/countly-server/pull/5230#top)"

```
Error: Cannot find module 'tslib'
Require stack:
- /opt/countly/node_modules/xlsx-write-stream/dist/XLSXTransformStream.js
- /opt/countly/node_modules/xlsx-write-stream/dist/index.js
```

While I don't see any reference for tslib in the xlsx-stream, but when I check the dist code in node_modules it does require it:

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
const archiver_1 = tslib_1.__importDefault(require("archiver"));
const stream_1 = require("stream");
const XLSXRowTransform_1 = tslib_1.__importDefault(require("./XLSXRowTransform"));
const templates = tslib_1.__importStar(require("./templates"));
```

So maybe it needs to be added as a dependency?

**Comment by jirimoravcik** [comment]
Hello, @ar2rsawseen,
thank you for reporting this issue.
I've just released version `1.0.3`, which fixes the problem.
