### ISSUE TITLE
How to run the test

### ISSUE THREAD

**Issue by jennyzzz** [Apifier/xlsx-stream#3]
Hi,

One of my projects depends on xlsx-stream, and I am considering adding a feature to support one of my use cases. Given the new feature would involve some logic, I would like to add some unit tests for it. However, I am having trouble running the existing test. I tried both running it in WebStorm and running it using command line. They both report the same error: 

(function (exports, require, module, __filename, __dirname) { import { expect } from 'chai';
                                                                     ^
SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    (and multiple lines down here...)

So essentially, it does not recognize "expect" from chai. 

Would you please instruct me on how to run the test?

While we are one this, I would also love to know how to build the project itself into a module so that my other project can depend on the local build instead of the npm one. This would be easier for me to verify my change. 

Thank you very much!

Jenny

**Comment by gippy** [comment]
Hi Jenny,

sorry for not replying sooner. I just saw your pull request.

Did you manage to run the tests/build the project?

If not, I will try it today (maybe some dependency is outdated) and send you details of how to do both actions (it should be just `npm run test` and `npm run build` but it's never that easy.

I will let you know.
Jaroslav

**Comment by jennyzzz** [comment]
Hi Jaroslav,

Thank you for your reply. I could build and run the tests successfully now.

Feel free to let me know if the pull request has any problems.

Thank you again for your contributions on this awesome project!

Best Regards,
Jenny
